//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A battle over predicate has not been set. Be sure to call SetBattleOverCondition..
        /// </summary>
        internal static string ARENA_BUILDER_NO_BATTLE_END_CONDITION_SET {
            get {
                return ResourceManager.GetString("ARENA_BUILDER_NO_BATTLE_END_CONDITION_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arena hasn&apos;t been made yet - try calling SetNumberOfSides first..
        /// </summary>
        internal static string ArenaNotStarted {
            get {
                return ResourceManager.GetString("ArenaNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams list cannot be null or empty..
        /// </summary>
        internal static string EmptyOrNullTeamListExceptionMessage {
            get {
                return ResourceManager.GetString("EmptyOrNullTeamListExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current turn scheme is invalid..
        /// </summary>
        internal static string InvalidTurnScheme {
            get {
                return ResourceManager.GetString("InvalidTurnScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A team hasn&apos;t been added to this arena yet..
        /// </summary>
        internal static string NoTeamAddedArenaBuilder {
            get {
                return ResourceManager.GetString("NoTeamAddedArenaBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start has not been called - no team was being built..
        /// </summary>
        internal static string START_NOT_CALLED_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("START_NOT_CALLED_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A turn manager has not yet been set..
        /// </summary>
        internal static string TURN_MANAGER_NOT_SET {
            get {
                return ResourceManager.GetString("TURN_MANAGER_NOT_SET", resourceCulture);
            }
        }
    }
}
